export const GET_HISTORIC = 'GET_HISTORIC';
export const INFO_MONEY_DONE = 'INFO_MONEY_DONE';
export const SET_OBJECTIVE = 'SET_OBJECTIVE';
export const SET_CREDIT = 'SET_CREDIT';
export const SET_DEBITS_MONTH = 'SET_DEBITS_MONTH';
export const SET_DEBITS_NEXT_MONTH = 'SET_DEBITS_NEXT_MONTH';